# This workflow will install Python, tahoe and run unittests
# installing tahoe ensures dependencies are installed

name: unittests

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Setup tahoe
      run: |
        python setup.py install
    - name: Test with unittest
      run: |
        cd tahoe
        python -m unittest
